# Generated by Django 6.0.5 on 2026-05-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
