# Generated by Django 6.0.5 on 2026-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('buyer', 'Buyer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
